name: Prod Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build-frontend:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Establish ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /webapps/Hacktoberfest_website
            sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
            sudo chmod g+rwx "$HOME/.docker" -R
            git fetch        
            git pull         
            docker compose -f docker-compose.yml up -d --build
