name: Prod Server Logs

on:
  workflow_dispatch:

jobs:
  logs:
    name: Fetch Logs
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and get logs
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /webapps/Hacktoberfest_website
            docker compose -f docker-compose.yml logs --tail=5000
